const fs = require('fs');

let content = fs.readFileSync('c:/Users/devlp/OneDrive/Desktop/antigravity/profileSite/Profilesite/index.html', 'utf8');

const metroBefore = `<div><p class="mb-2 text-xs uppercase tracking-widest text-muted-foreground">Problem</p><div class="text-foreground">Commuters dropped off at unpredictable points in the journey. Stakeholders disagreed on which moments mattered most.</div></div><div><p class="mb-2 text-xs uppercase tracking-widest text-muted-foreground">Process</p><div class="text-foreground"><ul class="space-y-2"><li class="flex gap-3"><span class="mt-2.5 h-1 w-1 shrink-0 rounded-full bg-accent"></span><span>Mixed-method research: 24 interviews + behavioral analytics on 6 weeks of trip data</span></li><li class="flex gap-3"><span class="mt-2.5 h-1 w-1 shrink-0 rounded-full bg-accent"></span><span>AI-assisted synthesis to cluster friction points across user segments</span></li><li class="flex gap-3"><span class="mt-2.5 h-1 w-1 shrink-0 rounded-full bg-accent"></span><span>Cross-functional workshops to align product, ops and design on top 3 problem spaces</span></li><li class="flex gap-3"><span class="mt-2.5 h-1 w-1 shrink-0 rounded-full bg-accent"></span><span>Iterative prototyping and in-context usability testing on platform</span></li></ul></div></div><div><p class="mb-2 text-xs uppercase tracking-widest text-muted-foreground">Solution</p><div class="text-foreground">Simplified information hierarchy, removed redundant decision points, and surfaced confidence cues at moments of doubt.</div></div>`;

const metroAfter = `<div><p class="mb-2 text-xs uppercase tracking-widest text-muted-foreground">Before: The Messy Reality</p><div class="text-foreground">Commuters dropping off at unpredictable journey points. Stakeholders disagreed on which moments mattered most. Data was siloed across 6 weeks of chaotic trip logs.</div></div><div><p class="mb-2 text-xs uppercase tracking-widest text-muted-foreground">After: The Shipped Code</p><div class="text-foreground">A streamlined real-time transit dashboard that simplified information hierarchy, removed redundant decision points, and surfaced confidence cues precisely at moments of doubt.</div></div><div><p class="mb-2 text-xs uppercase tracking-widest text-muted-foreground">Tech Stack</p><div class="flex flex-wrap gap-2 text-sm text-foreground"><span class="rounded-full border border-hairline bg-surface px-3 py-1">Vue.js</span><span class="rounded-full border border-hairline bg-surface px-3 py-1">Mapbox GL</span><span class="rounded-full border border-hairline bg-surface px-3 py-1">Node.js</span></div></div>`;


const gnBefore = `<div><p class="mb-2 text-xs uppercase tracking-widest text-muted-foreground">Problem</p><div class="text-foreground">First-time users abandoned setup of hearing-care apps before reaching value. The team lacked a clear behavioral model of why.</div></div><div><p class="mb-2 text-xs uppercase tracking-widest text-muted-foreground">Process</p><div class="text-foreground"><ul class="space-y-2"><li class="flex gap-3"><span class="mt-2.5 h-1 w-1 shrink-0 rounded-full bg-accent"></span><span>Discovery research with hearing-impaired users across age cohorts</span></li><li class="flex gap-3"><span class="mt-2.5 h-1 w-1 shrink-0 rounded-full bg-accent"></span><span>Mapped emotional and cognitive barriers in onboarding</span></li><li class="flex gap-3"><span class="mt-2.5 h-1 w-1 shrink-0 rounded-full bg-accent"></span><span>Validated solutions through prototype testing</span></li><li class="flex gap-3"><span class="mt-2.5 h-1 w-1 shrink-0 rounded-full bg-accent"></span><span>Extended a scalable design system to keep changes consistent</span></li></ul></div></div><div><p class="mb-2 text-xs uppercase tracking-widest text-muted-foreground">Solution</p><div class="text-foreground">Re-sequenced onboarding around user-perceived progress, added contextual reassurance, and standardized accessibility tokens in the design system.</div></div>`;

const gnAfter = `<div><p class="mb-2 text-xs uppercase tracking-widest text-muted-foreground">Before: The Messy Reality</p><div class="text-foreground">First-time users abandoned the setup of hearing-care apps before reaching value, bogged down by a complex, high-friction onboarding flow without a clear behavioral model.</div></div><div><p class="mb-2 text-xs uppercase tracking-widest text-muted-foreground">After: The Shipped Code</p><div class="text-foreground">Re-sequenced onboarding built around user-perceived progress, adding contextual reassurance and standardizing accessibility tokens across a newly shipped design system.</div></div><div><p class="mb-2 text-xs uppercase tracking-widest text-muted-foreground">Tech Stack</p><div class="flex flex-wrap gap-2 text-sm text-foreground"><span class="rounded-full border border-hairline bg-surface px-3 py-1">React Native</span><span class="rounded-full border border-hairline bg-surface px-3 py-1">TypeScript</span><span class="rounded-full border border-hairline bg-surface px-3 py-1">TailwindCSS</span></div></div>`;

const carlsbergBefore = `<div><p class="mb-2 text-xs uppercase tracking-widest text-muted-foreground">Problem</p><div class="text-foreground">Internal teams made high-stakes pricing decisions in tools that obscured cost structures, leading to errors and slow approvals.</div></div><div><p class="mb-2 text-xs uppercase tracking-widest text-muted-foreground">Process</p><div class="text-foreground"><ul class="space-y-2"><li class="flex gap-3"><span class="mt-2.5 h-1 w-1 shrink-0 rounded-full bg-accent"></span><span>Shadowed pricing analysts to map real workflows and decision points</span></li><li class="flex gap-3"><span class="mt-2.5 h-1 w-1 shrink-0 rounded-full bg-accent"></span><span>Identified where users hesitated, second-guessed or escalated</span></li><li class="flex gap-3"><span class="mt-2.5 h-1 w-1 shrink-0 rounded-full bg-accent"></span><span>Translated behavioral findings into clearer cost decomposition patterns</span></li><li class="flex gap-3"><span class="mt-2.5 h-1 w-1 shrink-0 rounded-full bg-accent"></span><span>Prototyped and validated with end-users before development handoff</span></li></ul></div></div><div><p class="mb-2 text-xs uppercase tracking-widest text-muted-foreground">Solution</p><div class="text-foreground">Restructured the pricing canvas around the decision being made — not the data being shown — with progressive disclosure for complexity.</div></div>`;

const carlsbergAfter = `<div><p class="mb-2 text-xs uppercase tracking-widest text-muted-foreground">Before: The Messy Reality</p><div class="text-foreground">Internal teams making high-stakes pricing decisions in cumbersome, obscure spreadsheets that hid cost structures, leading to decision errors and painfully slow approvals.</div></div><div><p class="mb-2 text-xs uppercase tracking-widest text-muted-foreground">After: The Shipped Code</p><div class="text-foreground">A custom progressive-disclosure pricing canvas that structures decisions logically, revealing complex calculations only when needed, backed by a robust audit trail.</div></div><div><p class="mb-2 text-xs uppercase tracking-widest text-muted-foreground">Tech Stack</p><div class="flex flex-wrap gap-2 text-sm text-foreground"><span class="rounded-full border border-hairline bg-surface px-3 py-1">Angular</span><span class="rounded-full border border-hairline bg-surface px-3 py-1">.NET Core</span><span class="rounded-full border border-hairline bg-surface px-3 py-1">D3.js</span></div></div>`;

content = content.replace(metroBefore, metroAfter);
content = content.replace(gnBefore, gnAfter);
content = content.replace(carlsbergBefore, carlsbergAfter);

fs.writeFileSync('c:/Users/devlp/OneDrive/Desktop/antigravity/profileSite/Profilesite/index.html', content);
console.log("Done updating index.html");
